spring:
  datasource:
    username: root
    password: Password
    #  url: jdbc:mysql://localhost:3306/store?useSSL=false
#    url: jdbc:mysql://localhost:3306/store
    url: jdbc:mariadb://localhost:3306/store
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect


